//directs the function to work once the page has loaded.
window.onload=function(){
        //change all links that have #section- in them which goes to the all sections page, to &section= links that go to the single section instead
$('nav a, .bookexit').each(function(){
        this.href=this.href.replace('#section-','&section=');
      //opens the atto editor completely on load    
    $('.editor_atto_toolbar div').removeAttr('hidden');
    $('.editor_atto_toolbar div').css('display', 'inline-block');
//opens the tinyMCE toolbar rows 2 and 3 on load (once a user collapses this again, it stops working)
    $('.mceToolbarRow2').css('display', 'table');
    $('.mceToolbarRow3').css('display', 'table');
    });
        //style library block to be like the others
    $("#inst3127749 ol li a").removeAttr("style");
    $('#inst3127749 .list a').css({"color": "#006DAE","text-decoration": "none !important","font-size": "1.1rem"});
    $('#inst3127749 ol').css({"border":"2px solid #f0f0f0", "border-radius":"5px","padding":"12px"});
        //make + icons change to - on click
    $(".collapse").on('show.bs.collapse', function(){
        	$(this).prev(".card-header").find(".fa").removeClass("fa-plus").addClass("fa-minus");
        }).on('hide.bs.collapse', function(){
        	$(this).prev(".card-header").find(".fa").removeClass("fa-minus").addClass("fa-plus");
        });
        //remove unit guide link from all S2 2020 sites
        $(".header-title:contains(S2 2020)").filter(function(){
    $('#arts-guide').remove();
        });
        //add how to's link to the nav banner if you are a tutor, lect, non-primary lect, designer or admin
$(".block-region .type_course a").each(function(){
    if($(this).text().match(/Recycle bin/)){
//link to how to's in the uni wide banner and nav drawer
	    $( ".header-right" ).prepend('<div class="custom-menus my-auto"><a href="https://lms.monash.edu/course/view.php?id=48399&section=14" target="_blank" class="border border-dark rounded-circle text-dark p-2" role="button" title="Ed Tech how tos"><i class="fa fa-bolt fa-fw" aria-hidden="true"></i></a></div>');
	    $( "#nav-drawer .list-group" ).prepend('<a class="list-group-item list-group-item-action" href="https://lms.monash.edu/course/view.php?id=48399&section=14" target="_blank" data-key="coursehome" data-isexpandable="0" data-indent="0" data-showdivider="0" data-type="60" data-nodetype="0" data-collapse="0" data-forceopen="0" data-isactive="0" data-hidden="0" data-preceedwithhr="0"><div class="ml-0"><div class="media"><span class="media-left"><i class="icon fa fa-bolt fa-fw " aria-hidden="true"></i></span><span class="media-body ">Ed Tech how tos</span></div></div></a>');
//instructions for staff that need to be switched off at 0 week
	    $('#welcome').before('<div class="staffInstructions alert alert-mu rounded">Provide students with an introductory video message in order to foster familiarity and establish a comfortable learning environment. It is especially important in the digital space to provide a personal and friendly welcome to your students.</div>');
	    $('#synopsis').before('<div class="staffInstructions alert alert-mu rounded">These should be the same as students will find in the handbook. Replicate them here so they are readily accessible by students. <a id="handbookLink" href="https://handbook.monash.edu/" target="_blank">Go to the handbook</a></div>');
	    $('#keyDates').before('<div class="staffInstructions alert alert-mu rounded">Refer students to the key dates students need to diarise.</div>');
	    $('#aboutSection').before('<div class="staffInstructions alert alert-mu rounded">A high-quality, head and shoulders, professional photo of all teaching staff in the unit, and an introduction from each, encourages rapport and reassures students that there is educator presence in the unit. Contact information should include available hours and preferred method for student communication.</div>');
	    $('#teachingLearning').before('<div class="staffInstructions alert alert-mu rounded">Provide explicit direction to students on how learning happens in your unit, and your expectations for student participation, contributions and engagement with their learning. Explain to students what they can expect to find in the moodle site, and how they should use the site. Creating consistent, purposeful and signposted learning pathways increases students’ sense of orientation within the unit and reduces confusion. This information will help students to develop skills and recognise attributes essential for success in the digital learning environment.</div>');  
	    $('#introWeekSequence').before('<div id="introFirstSequence" class="staffInstructions alert alert-mu rounded"><p><strong>A note on the design of the week/topic/module page:</strong> Ensure each week is presented in a consistent, logical way, with consideration of the following key elements:</p><ul><li><strong>Signposting:</strong> a clear learning pathway, or \'roadmap\', for the week. This example uses the pre-class/in-class/post-class structure to organise material. Other learning pathways include ‘Prepare, Explore, Apply’, and ‘Something to read, something to watch, something to discuss’. Talk to the Education Design team for some ideas on how to structure your learning material.</li><li><strong>Instructions:</strong> clear instructions for the students to help them understand how you would like them to progress through the materials and activities and explain what you are expecting them to learn. Further details can be provided within the activity to avoid too much text on the weekly page.</li><li><strong>Contextualisation:</strong> conceptual connections between resources, activities and assessment. This information makes it clear to students the purpose and rationale for the content and activities, and how they will achieve the learning objectives for the week. What’s important about this resource/activity? What do you expect students to gain from this?</li><li><strong>Content:</strong> a variety of content styles (eg, text, readings, videos, images and interactive activities) are packaged so that they fit on a screen and are easily navigable for students.</li><li><strong>Design:</strong> ensure accessibility and usability of the site by all your students (and screen readers). Use black text on a white background; instead of using colour to create emphasis, use heading options or text format options such as bold, italic and underline features; left-align text to optimise readability; use spacing, indenting, numbering and bullet points to break down larger pieces of text.</li></ul></div>');
	    $('#introFirstSequence').after('<div class="staffInstructions alert alert-mu rounded">Provide a welcoming introduction to each week. List the learning objectives or goals for the week. Clearly indicate the relationship between this week and one or more assessment tasks. This information helps students to prepare for the learning tasks ahead and can act as a motivator if the connection is clear between the weekly content and the unit\'s assessment.</div>');
	    $('#preClass').before('<div class="staffInstructions alert alert-mu rounded"><p>Pre-class learning activities prepare students to engage in deep learning in the classroom (physical or virtual). In the Arts Faculty, the preferred approach for online teaching is to transform (rather than replicate) the traditional lecture, by reimagining how you might teach using the advantages of the available technologies. This includes using a mixture of asynchronous (e.g., recorded videos, polls, forums) and synchronous (e.g., zoom) activities. You might even choose to remove your synchronous class altogether and instead utilise the full functionality of moodle to create rich, challenging and engaging tasks where students can apply their learning.</p><p>The templates below enable you to curate the following content and materials for students, considering the sequencing of the learning experience, and based on the learning goals for the week:</p><ul><li>Short lecturer-created videos to introduce key concepts, theories, frameworks</li><li>Key readings with guiding questions, signposting for students</li><li>Curated content such as youtube clips, websites</li><li>Opportunities for students to explore and apply the new concepts through a variety of activities</li><li>Opportunities for students to interact with other</li><li>Check points for student learning such as self-assessment, check/reflect on learning, both assessed/non-assessed</li><li>Establish and maintain a rapport with students and provide opportunities for consultation</li><li>Further readings and resources to support assessment and extend students</li></ul><p>Decide whether you will deliver your content using a Moodle lesson or Moodle book:</p><ul><li><img src="https://lms.monash.edu/theme/image.php/monash/lesson/1588788791/icon" alt="Moodle lesson icon" />Lessons provide a structure for a set learning sequence where content is scaffolded and linked. Lesson content can be interspersed with check-your-learning questions and activities that you can connect through to gradebook. You can set restrictions in a lesson so students cannot progress through the material unless they complete a question or activity.</li><li><img src="https://lms.monash.edu/theme/image.php/monash/book/1588788791/icon" alt="Moodle book icon" />Books provide a more flexible, open structure where students can access \'chapters\' in any order.</li></ul></div>');
	    $('#inClass').before('<div class="staffInstructions alert alert-mu rounded">[If applicable] Provide a brief overview of the virtual/physical in-class component. What can students expect? What is the connection to assessment activities? Include links to zoom sessions. Any further information, such as zoom instructions or an agenda for the class, should be provided within the activity to avoid too much text on the page.</div>');
	    $('#postClass').before('<div class="staffInstructions alert alert-mu rounded">How will you know that learning is successful? Ask students to complete a quiz, engage in a Moodle forum or submit a specific task to show they have mastered the concepts.</div>');
	    $('#assessmentSummary').before('<div class="staffInstructions alert alert-mu rounded"><p>The assessment page should include a summary of assessments, individual assignment instructions, assessment support resources and rubrics. Be explicit and transparent with students about the purpose of the task, the task requirements, and the marking criteria.</p><p><strong>A note on marking rubrics:</strong> marking rubrics are required for all assessment tasks except quizzes. Marking rubrics make explicit to students what they need to do against specific criteria to achieve a particular grade.</p></div>');
	    $('#assessmentSummary').after('<div class="staffInstructions alert alert-mu rounded"><p>Use the table below to summarise the assignments - the task title, value and due dates including submission times if applicable. Individual assignment instructions should include the details of the task as follows:</p><ul><li>the purpose of the task - why are you asking students to do it? What is the rationale/purpose of the task? What are the connections to learning in the unit, and to the learning outcomes for the unit?</li><li>the task - what exactly do you want students to do?</li><li>the marking criteria - how will the task be evaluated? Provide transparent marking criteria in a marking rubric.</li></ul></div>');
	    $('#assessmentOneInstruction').after('<div class="staffInstructions alert alert-mu rounded"><ul><li>Include links/instructions for submission and Turnitin if applicable.</li><li>Ensure any support resources such as exemplars, or a forum for questions about the assessment, are located in the relevant assessment section. If you have several support documents, you may choose to file them under a folder.</li><li>Once you have completed your assessment page setup, ensure your <a href="https://lms.monash.edu/grade/report/index.php?id=000">unit\'s gradebook</a> accurately represents how your unit will be assessed. Your <a href="https://www.intranet.monash/arts/academic-governance-students/teaching-support/contact-us" target="_blank">teaching support member</a> can assist with this.</li></ul></div>');
	    $('#announcementsForum').before('<div class="staffInstructions alert alert-mu rounded">Provide meaningful opportunities for students to connect with their peers and with you in your moodle site. Social presence in the digital learning environment is a key factor in student motivation, participation, engagement and experience. This is especially important where your students may not regularly see you or their peers in a physical classroom.</div>');
	    $('#generalUnitForum').before('<div class="staffInstructions alert alert-mu rounded"><p>In addition to the activity-specific forums you may utilise in the weekly learning activities, and the assignment forums for questions about specific assessment tasks, there are several different uses for forums in Moodle. These include:</p><ul><li>announcements as a help centre (one-way communication, students cannot respond)</li><li>a standard forum where anyone can start a new discussion at any time:<ul><li>to allow for socialising within the Moodle site, as students do not know who is in the cohort as Moodle keeps this information private.</li><li>to ask general questions about the unit materials that are not answered elsewhere. This is a centralised approach to communication, that may work better for your context than responding to individual student emails.</li></ul></li><li>Q & A where students respond to a thread the lecturer starts, and then see all other student responses.</li></ul><p>This section or the overview section (or both) is a great opportunity to scaffold how you want students to communicate with the teaching staff, and with each other. Provide instructions on what you are comfortable with students emailing you for - special consideration, extensions - and where you want certain questions posted - assessment questions in the assessment section, general questions not answered elsewhere in the communication section, weekly activities in the forums within the weeks.</p><p>You can also set activity completion options such as the number of times a student can post to a forum, and require a certain number of posts and responses. You can require students respond to others\' posts as evidence of their participation. Students can also post links, images, audio and video in forums to enrich the conversation.</p></div>');
	    $('#digitalReadingList').before('<div class="staffInstructions alert alert-mu rounded"><p>The digital reading list can be set up through the library and is a central resource students depend on for reviewing learning content throughout the teaching period. It is incredibly important this is setup correctly once you have received confirmation from the library that your list is ready. The library will send you a direct link to the Talis list. Do not put this link in your Moodle site. It is sent to you to be able to quickly check if the library has set it up correctly, not to be shared with students. There are two ways to setup the external tool for your list. Click the link below to be taken to instructions for the relevant setups (links open in a new window):</p><ul><li><a href="https://lms.monash.edu/mod/book/view.php?id=7450900&section=16" target="_blank">Basic setup</a></li><li><a href="https://lms.monash.edu/mod/book/view.php?id=7450900&chapterid=741300" target="_blank">Advanced setup</a></li></ul></div>');
	    $('#accessThreeSixty').before('<div class="staffInstructions alert alert-mu rounded">This external tool is linked to Echo 360, the university’s lecture capture service. If you have any time set up in spaces where recording is available, they will become available to students shortly after completing the recording.</div>');
	    $('#studentSupportResources').before('<div class="staffInstructions alert alert-mu rounded">The page resources here contain links to Faculty and University level support services for students. These include technical support, mental health support, student interest groups and disability support.</div>');
	    $('#industryResources').before('<div class="staffInstructions alert alert-mu rounded">Resources here connect the learner and the content to real world organisations, case studies, careers in the field and general application of the knowledge and skills addressed in your unit. These may be journals, web sites or interesting roles in the field you are aware of.</div>');
  };
});
	$(".block-region .type_course a").each(function(){
		if($(this).text().match(/Restore/)){
var userName = document.querySelector('.myprofileitem.fullname')
? document.querySelector('.myprofileitem.fullname').innerText
: null;
	if(userName == "Tim Scholl" || userName == "Sneha Mohandas" || userName == "Tahlia Birnbaum" || userName == "Carmen Sapsed" || userName == "Josephine Hook"){
		$(".header-right").prepend('<div class="custom-menus my-auto dropdown"><button type="button" target="_blank" class="border border-dark rounded-circle p-2 text-dark" role="button" title="BEEST" style="width:38px; height: 38px;" data-toggle="modal" data-target=".beest-home-modal" id="beestDropdown"><img src="https://mon-arts-ed-des.github.io/BEEST/img/dragon-solid-black.png" width="20px" height="20px" style="margin-bottom: 4px;" /></button>');
		$("#region-main").append('<style>.modal-beest{max-width: 80% !important;}</style><div class="modal fade beest-home-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true"><div class="modal-dialog modal-lg modal-beest"><div class="modal-content"><div class="modal-header mb-0 p-2 bg-danger text-white px-5"><h5 class="modal-title text-white my-auto" id="exampleModalLabel">To close this window click the button on the right or anywhere outside this box.</h5><button type="button" class="btn btn-outline-light btn-lg rounded" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Close <i class="fa fa-times"></i></span></button></div><iframe src="https://mon-arts-ed-des.github.io/BEEST/index.html" width="100%" height="900px"></iframe></div></div></div>');
	};
		};
	});
};
